In [85]:
import numpy as np
import scipy as sp
import MDAnalysis as mda

In [44]:
tpr_file = 'ruyin_helix/system2_minim.tpr'
gro_file = 'ruyin_helix/system2_minim.gro'
u = mda.Universe(gro_file)

In [45]:
protein = u.select_atoms('protein')

In [46]:
protein.principal_axes()

array([[-0.0321192 , -0.41489436, -0.9093025 ],
       [-0.98865125,  0.14677104, -0.0320463 ],
       [-0.1467551 , -0.89795375,  0.41489999]])

In [47]:
membrane = u.residues[u.residues.resnames == 'POC']

In [130]:
poc1 = membrane[0].atoms
poc1.center_of_mass()

array([ 42.55013205,   5.32892837,  43.86621689])

In [133]:
membrane[0].center_of_mass()

array([ 42.55013205,   5.32892837,  43.86621689])

In [107]:
[x for x in poc1.names if x[:2] == 'C2']

['C2',
 'C21',
 'C22',
 'C23',
 'C24',
 'C25',
 'C26',
 'C27',
 'C28',
 'C29',
 'C210',
 'C211',
 'C212',
 'C213',
 'C214',
 'C215',
 'C216',
 'C217',
 'C218']

In [145]:
c2 = poc1.names[poc1.names == 'C2']
c2

array(['C2'], 
      dtype='|S4')

In [125]:
for indx,x in enumerate(poc1.names):
    if x[:2] == 'C2':
        print indx,x

27 C2
30 C21
32 C22
44 C23
47 C24
50 C25
53 C26
56 C27
59 C28
62 C29
64 C210
66 C211
69 C212
72 C213
75 C214
78 C215
81 C216
84 C217
87 C218


In [114]:
itemindex = np.where(poc1.names==c2)
itemindex[0][0]

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [168]:
head = poc1[:itemindex[0][0]]
head
head.center_of_mass()

<AtomGroup with 134 atoms>


array([ 43.75713739,   6.98145704,  50.95923307])

In [167]:
tails = poc1[itemindex[0][0]:]
tails
tails.center_of_mass()

array([ 42.13027387,   4.75409438,  41.39890309])

In [142]:
#selecting membrane, lipid tail and heads
def membrane_mass_centers(universe, lipidresiduename, separationatomname):
    #select the mambrane:
    membrane = universe.residues[universe.residues.resnames == lipidresiduename]
    
    #separete heads
    heads = []
    for l in membrane:
        lat = l.atoms
        itemindex = np.where(lat.names==separationatomname)
        head = lat[:itemindex[0][0]]
        heads.append(head)
        
    #centers of mass of heads:
    headsCenters = []
    for h in heads:
        headsCenters.append(h.center_of_mass())
    
    #separate tails:
    tails = []
    for l in membrane:
        lat = l.atoms
        itemindex = np.where(lat.names==separationatomname)
        tail = lat[itemindex[0][0]:]
        tails.append(tail)
        
    #centers of mass of heads:
    tailsCenters = []
    for t in tails:
        tailsCenters.append(t.center_of_mass())
    
    #centers of mass of lipids:
    membraneCenters = []
    for l in membrane:
        lat = l.atoms
        membraneCenters.append(lat.center_of_mass())
        
        
        
    for indx,x in enumerate(poc1.names):
    if x[:2] == 'C2':
        print indx,x
    #seperate tail1:
    tail1=[]
    for indx,x in enumerate(poc1.names):
    if x[:2] == 'C2':
        print indx,x
    
    #seperate tail2:
    
    #center of mass of tails1:
    
    #center of mass of tails2:
        
    return membraneCenters, headsCenters, tailsCenters

In [143]:
#seting the cutof:

In [149]:
membrane_mass_centers(u, 'POC', 'C2')

([array([ 42.55013205,   5.32892837,  43.86621689]),
  array([ 44.43780778,  50.58952995,  42.63291122]),
  array([ 48.51171389,  41.76166688,  45.78834941]),
  array([ 61.85453596,  59.3171129 ,  48.49877205]),
  array([ 35.62660724,  12.42737335,  47.84453481]),
  array([ 43.19085037,  26.30878763,  48.91846691]),
  array([ 15.9339657 ,  16.51791029,  46.80540841]),
  array([ 31.20666997,  55.43777061,  46.87063911]),
  array([ 39.27658475,  46.20871772,  42.77429363]),
  array([ 52.33431652,  52.50638128,  46.37367773]),
  array([ 16.71528114,  66.39084926,  45.94800866]),
  array([ 19.38474839,  25.65166219,  46.65298093]),
  array([ 32.93264876,  33.69116314,  47.79482296]),
  array([ 27.8788823 ,  19.52148476,  48.93392666]),
  array([ 24.7461253 ,  12.57323301,  49.60439798]),
  array([ 25.74632435,  55.36806905,  44.75027614]),
  array([ 60.14497847,  35.73723032,  49.0158998 ]),
  array([ 21.37692133,  47.94232096,  47.18800808]),
  array([ 53.44837581,  37.19202849,  47.62848

In [204]:
#trying different data:
gro_file = 'Band3_traj/band3.gro'
xtc_file = 'Band3_traj/band3.xtc'

ul = mda.Universe(gro_file, xtc_file)
membrane = ul.residues[u.residues.resnames == 'POPC']


In [208]:
membrane = ul.select_atoms("resname POPC or resname POC")

In [222]:
for ts in ul.trajectory[:3]:
    center = membrane.centroid()
    d = np.sqrt(np.sum((membrane.positions - center)[:, :2]**2, axis=1))
    print d

[ 29.37519073  31.66588211  30.27944374 ...,  43.56996155  44.4649086
  45.52062225]
[ 30.20598221  31.38982582  31.8880806  ...,  41.23901367  40.42560577
  40.05081177]
[ 29.41552734  31.6311264   30.92515945 ...,  34.95473099  33.39573288
  32.79282379]


In [221]:
np.sqrt(np.sum((membrane.positions - center)[:, :2]**2, axis=1))

array([ 29.41552734,  31.6311264 ,  30.92515945, ...,  34.95473099,
        33.39573288,  32.79282379], dtype=float32)

In [182]:
membrane_mass_centers(u, 'POPC', 'C13')

([array([ 12.90757632,  17.813292  ,  61.48989063]),
  array([ 54.22362338,  49.40762193,  62.89922956]),
  array([ 12.4731282,  45.8809654,  60.8572682]),
  array([  9.67074134,  49.51090835,  37.48968595]),
  array([ 16.43028481,  48.62126659,  36.6070561 ]),
  array([ 66.56860094,  25.85805838,  35.01071351]),
  array([ 68.22636177,  12.75380333,  40.07937977]),
  array([ 19.49965281,   7.52275568,  35.44988233]),
  array([ 11.37274679,  61.68385136,  58.26501051]),
  array([ 51.5831076 ,  43.10689806,  35.82764877]),
  array([ 68.26599681,  52.17458665,  61.91011934]),
  array([ 45.36754484,  67.71384993,  38.23367024]),
  array([ 55.89218943,  46.8575119 ,  38.21066299]),
  array([ 63.88474062,  22.77483857,  36.86624387]),
  array([ 35.60864319,  58.45849574,  34.68094391]),
  array([ 21.15632748,  28.74043489,  62.75738873]),
  array([ -2.03367875,   5.46502572,  36.57575911]),
  array([ 28.89385153,  24.92267245,  36.98459929]),
  array([ 44.81932863,  27.06992293,  62.35504081

In [171]:
#seperate tail1:
tail1=[]
for x in membrane:
    lat=x.atoms.names
    for i in xrange(0,len(lat)):
        if lat[i][:2] == 'C2':
            #print i,lat[i]
            tail1.append(x.atoms[i])
        
print tail1     

[<Atom 634: C2 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 637: C21 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 639: C22 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 651: C23 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 654: C24 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 657: C25 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 660: C26 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 663: C27 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 666: C28 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 669: C29 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 671: C210 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 673: C211 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 676: C212 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 679: C213 of type C of resname POC, resid 41 and segid SYSTEM>, <Atom 682: C214 of type C of r

In [ ]:

    if lat[:2] == 'C2':
        print indx,lat