In [11]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import MDAnalysis as mda
import MDAnalysis.analysis.helanal
import geometry
import lipidsCenters

In [2]:
tpr_file = 'ruyin_helix/system2_minim.tpr'
gro_file = 'ruyin_helix/system2_minim.gro'
xtc_File = 'Band3_traj/band3.xtc'
u = mda.Universe(gro_file)

In [6]:
protein = u.select_atoms('protein')

In [10]:
protein.principal_axes()

array([[-0.0321192 , -0.41489436, -0.9093025 ],
       [-0.98865125,  0.14677104, -0.0320463 ],
       [-0.1467551 , -0.89795375,  0.41489999]])

In [11]:
calpha = u.select_atoms('name CA')

In [26]:
rlist = []

for ts in u.trajectory:
    # Select the C_alpha atoms in the trajectory (assumes there is only one helix)
    calpha = u.select_atoms('name CA')
    # Calculate the principal axis 
    princ = calpha.principal_axes()
    print princ
    print geometry.tilt(calpha)
    com_calpha = calpha.center_of_mass()
    point = np.array([0,0,0])
    
    com_lipids, com_heads, com_tails = lipidsCenters.membrane_mass_centers(u,'POC','C2')
    
    for point in com_heads:
        r = geometry.dist_point_line(point,com_calpha,princ[0])
        rlist.append(r)
 
data = plt.hist(rlist)
count = data[0]
tics = data[1]

rdf = count/(2*3.14*tics[0:-1])


plt.plot(tics[0:-1],rdf)

plt.show()

[[-0.02233006 -0.42237291 -0.90614706]
 [-0.93927951  0.31930619 -0.12568834]
 [-0.34242572 -0.84831874  0.40385635]]
0.436712475452


In [15]:
math.pi

NameError: name 'math' is not defined